/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2tZRbgRawBx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"

export function Home() {
  return (
    <div className="dark">
      <header className="p-4 border-b grid place-items-center gap-4 sm:flex-1/0">
        <div className="flex items-center gap-4">
          <Link className="flex items-center gap-2" href="#">
            <HomeIcon className="h-6 w-6" />
            <span className="font-semibold">Home</span>
          </Link>
        </div>
        <nav className="flex items-center gap-4 text-sm ml-auto">
          <Link className="font-medium" href="#">
            Walkthrough
          </Link>
          <Link className="font-medium" href="#">
            Gallery
          </Link>
          <Link className="font-medium" href="#">
            About
          </Link>
        </nav>
      </header>
      <main className="flex-1 dark:bg-gray-800">
        <div className="grid md:grid-cols-2 gap-4 p-4 md:p-6">
          <div className="grid gap-4">
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 1"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Golden Sunset</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Alex Johnson</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                A stunning view of the sun setting over the horizon.
              </p>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 2"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Mountain Serenity</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Emily Parker</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Experience the calmness of the mountains in this serene shot.
              </p>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 3"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Coastal Beauty</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Michael Adams</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Capturing the beauty of the coast with its vibrant colors.
              </p>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 4"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Urban Exploration</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Sarah Lee</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Discover the hidden gems of the city through this exploration.
              </p>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 5"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Enchanting Forest</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by William Clark</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Lose yourself in the enchanting beauty of the forest.
              </p>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 6"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Tranquil Waters</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Olivia White</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Experience peace and tranquility by the waterside.
              </p>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 7"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">Majestic Peaks</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Daniel Taylor</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Witness the grandeur of the majestic mountain peaks.
              </p>
            </div>
            <div className="relative group overflow-hidden rounded-lg">
              <img
                alt="Thumbnail 8"
                className="aspect-video object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
                height={400}
                src="/placeholder.svg"
                width={600}
              />
              <h3 className="font-semibold mt-2 group-hover:underline text-white">City Skylines</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">by Jessica King</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Explore the dynamic cityscapes captured in this collection.
              </p>
            </div>
          </div>
        </div>
      </main>
      <footer className="border-t p-4 grid place-items-center text-sm gap-4 sm:flex-1/0">
        <div className="flex items-center gap-2">
          <p className="font-medium text-white">© 2023 Gallery</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <TwitterIcon className="w-5 h-5" />
            <span className="sr-only">Twitter</span>
          </div>
          <div className="flex items-center gap-2">
            <GithubIcon className="w-5 h-5" />
            <span className="sr-only">GitHub</span>
          </div>
          <div className="flex items-center gap-2">
            <DribbbleIcon className="w-5 h-5" />
            <span className="sr-only">Dribbble</span>
          </div>
        </div>
      </footer>
    </div>
  )
}

function DribbbleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M19.13 5.09C15.22 9.14 10 10.44 2.25 10.94" />
      <path d="M21.75 12.84c-6.62-1.41-12.14 1-16.38 6.32" />
      <path d="M8.56 2.75c4.37 6 6 9.42 8 17.72" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
